java_library(
    name="rpclib",
    srcs = glob([
        "com/google/gapid/rpclib/any/*.java",
        "com/google/gapid/rpclib/binary/*.java",
        "com/google/gapid/rpclib/futures/*.java",
        "com/google/gapid/rpclib/rpccore/*.java",
        "com/google/gapid/rpclib/schema/*.java",
    ]),
    visibility = ["//visibility:public"],
    deps=[
        "//gapic/third_party:guava",
    ],
)