load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = [
        "api.go",
        "expression.go",
        "function.go",
        "identifier.go",
        "invalid.go",
        "literal.go",
        "node.go",
        "operator.go",
        "type.go",
        "visit.go",
    ],
    visibility = ["//visibility:public"],
)
