cc_library(
    name = "cc",
    srcs = [
        "common.cpp",
        "libmanager.cpp",
        "name_manager.cpp",
        "spv_manager.cpp",
    ],
    hdrs = [
        "common.h",
        "libmanager.h",
        "name_manager.h",
        "spv_manager.h",
    ],
    deps = [
        "//third_party/khronos",
    ],
    visibility = ["//visibility:public"],
)