load("//tools/build:rules.bzl", "android_native")

android_native(
    name = "VkLayer_VirtualSwapchain",
    deps = ["//core/vulkan/vk_virtual_swapchain/cc:cc"],
    visibility = ["//visibility:public"],
)